ParaTime picker
oasisprotocol/explorer pull request #426
Opened 2023-05-23 21:02 UTC by buberdds

PR covers only desktop version

Need to go through this with Don tomorrow + there are some missing descriptions in lang files.

2023-05-24 21:46 UTC, lukaw3d commented on src/app/components/ParaTimePicker/ParaTimeMenu.tsx
> +            {activeLayer === layer && t('paraTimePicker.selected')}
Bug:
- open picker on testnet https://d35c4db7.oasis-explorer.pages.dev/testnet/emerald
- it shows Emerald Mainnet as currently selected
![image](https://github.com/oasisprotocol/explorer/assets/3758846/db0d8f81-c633-4fd6-a47a-49a355fdc9d0)

2023-05-24 21:46 UTC, lukaw3d commented on src/app/components/ParaTimePicker/ParaTimeMenu.tsx
> +        }}
I get annoyed with this UX:
![ux](https://github.com/oasisprotocol/explorer/assets/3758846/23f29c0a-8006-465d-bb71-35bff81d890a)

2023-05-24 21:46 UTC, lukaw3d commented on src/app/components/ParaTimePicker/index.tsx
> +        </Box>
(smaller screen layout issue: buttons sometimes overlay the text:
![image](https://github.com/oasisprotocol/explorer/assets/3758846/bea9390a-0a30-487d-926f-33bbd204ece4)

2023-05-24 21:46 UTC, lukaw3d commented on src/app/components/ParaTimePicker/index.tsx
> +          </Grid>
(smaller screen layout issue: with my scrollbars, buttons are sometimes jittery:
![button positions](https://github.com/oasisprotocol/explorer/assets/3758846/4f10e26f-5479-45cd-998e-3b6292e9577e)

2023-05-25 16:34 UTC, csillag commented
I checked this out, and have a few difficulties with with, and suggestions.

1. By default, we only see the level where we can select Paratimes within the network. There is no indication whatsoever that it should be possible to switch between networks. (Even when I am running in TestNet mode!) There is only this little arrow at the top, which is nor clear at all. I think at least a work of explanation would be very useful there.
2. When I click that semi-hidden button, the network selector is revealed, but it only shows the Mainnet, even if I am currently at TestNet! I understand that we don't want to promote TestNet too much, but when we are already on TestNet, what is the point of hiding it's existence? I think it's confusing that the opening state is not synced to the current setting. I think if we are at TestNet, it should shot TestNet selected by default.
3. Why is the currently selected state not highlighted by a different bg color? (Both network and Paratime.)

@donouwens I'm sorry to bring the feedback so late in the game, but I think it's better late then never.

2023-05-25 18:08 UTC, csillag commented
- For point 1: Having it collapsed is OK. All I am advocating for is having a single word of explanation besides the arrow.
- For point 3: For me, on my monitor, the difference between the selected and not selected stats is undetectable. About confusion with the hover state: the hover state has both the moving arrow _and_ the background color change. I think we could take one of the two to indicate the selected state. (Or something else, but the current way I just can not see.)

2023-05-25 22:35 UTC, lukaw3d approved these changes

2023-05-25 22:45 UTC, csillag commented
>  the active state does have a background in the designs. Has it not been implemented correctly? I feel there are significant color differences and visual indicators between default/selected/hover/disabled (which also has the tooltip) - see screenshot.

<img width="662" alt="Screenshot 2023-05-25 at 21 26 43" src="https://github.com/oasisprotocol/explorer/assets/2155682/c4feee31-225f-48eb-851d-676f54d7d44d">

   * * *

No, it doesn't look that way. This is the current implementation:

<img width=567 src="https://github.com/oasisprotocol/explorer/assets/2093792/6f7d4087-bd8c-480f-9569-c7e219b60f64" />


So,
 -  In the design, both the lighter shade of highlight, and the arrow signifies the current selection, and the hover is a stronger shade of highlight.
 - However, in the implementation, there is only one shade of highlight, and both it and the arrow serve the hover, and the selection only has the small "(currently active)" flag.

Should be easy to fix, though.

2023-05-25 22:46 UTC, csillag requested changes
Please make it so that the selected state is highlighted, like it is in the design. Maybe my eyes  👀  are not what they used to be, but I can hardly see which one is selected..

2023-05-25 22:55 UTC, csillag commented
>> When I click that semi-hidden button, the network selector is revealed, but it only shows the Mainnet, even if I am currently at TestNet! I understand that we don't want to promote TestNet too much, but when we are already on TestNet, what is the point of hiding it's existence? I think it's confusing that the opening state is not synced to the current setting. I think if we are at TestNet, it should shot TestNet selected by default.

> This is true - if the user is one Testnet we should show the Testnet icon or Testnet icon with 'Testnet' title.

That part works, we can see the Testnet icon and title, that's not what I'm talking about.
My issue is that when I bring out the network selector, it only shows Mainnet, and hides Testnet, _**which is the current selection**_. 

![image](https://github.com/oasisprotocol/explorer/assets/2093792/6946a842-afb4-43ae-89b2-9b44dc081dd5)

So, to summarize: we are on Testnet, why is testnet not listed as one of the options, and marked as selected?

2023-05-26 08:39 UTC, buberdds commented on src/app/components/ParaTimePicker/LayerMenu.tsx
> +    .sort((a, b) => menuSortOrder.indexOf(a.layer) - menuSortOrder.indexOf(b.layer))
thx, I will go with 1st proposal, but without negative values

2023-05-26 10:32 UTC, buberdds commented
@csillag 
- Network menu is open and expanded for non mainner networks
- hover and selected states updated based on Don's feedback. 

If I did not catch something else from your comment let me know 🖖

2023-05-26 10:49 UTC, csillag commented
>     * network menu is open and expanded for non mainnet networks

Yep, that works great now!

>     * hover and selected states updated based on Don's feedback

I'm sorry I still don't see the highlight color on the bg of the selected option.
I'm looking for this: <img width="662" alt="Screenshot 2023-05-25 at 21 26 43" src="https://github.com/oasisprotocol/explorer/assets/2155682/c4feee31-225f-48eb-851d-676f54d7d44d">

I do see the highlight for hover, but not for selection. In Don's visuals, there were two distinct highlights, one for hover, and one for selection.

2023-05-26 10:52 UTC, buberdds commented
I've received this from Don today. I will double check with him again.

1. default
2. hover
3. selected
4. disabled 

![Screenshot 2023-05-26 at 08 31 28](https://github.com/oasisprotocol/explorer/assets/891392/3b063bac-07f8-434f-a52b-56ded1924633)

2023-05-26 11:28 UTC, buberdds commented
Turns out there was an issue with mockups and some colors were wiped out :D Background to selected state added.

2023-05-26 11:32 UTC, csillag commented
I think it would make total sense to reassign the arrow for selection type 2 instead of type 1.
It's a nice connection between the left side (the option selected) and the right side (where the option is described).

2023-05-26 11:40 UTC, buberdds commented
Here's answer from Don: We have default, selected, disabled, active states. Let’s stick with those. The ‘mouse down’ state Kristof is describing is a split second state between hover and active. We are okay without it.

2023-05-26 11:44 UTC, csillag commented
OK, can clear up the dictionary? I am suspecting that we might assing different meaning to some of the terms here.
The state I'm talking about (selection type 2) is definitely not a split second state; it starts when the users clicks on the list item, and exists indefinitely, at least until the user clicks the "select" button at the other side of the dialog, hence closing the dialog.

2023-05-26 12:02 UTC, buberdds commented
imo it doesn't make sense to discuss such design changes via code review process. It's better to discuss this during Sync meeting. I will keep PR open until then.

2023-05-26 13:33 UTC, csillag approved these changes
LGTM

2023-05-26 13:34 UTC, merged